### ISSUE TITLE
V2.20_H35_2022_1101_N_ZX_002 - WI FI

### ISSUE THREAD

**Issue by small66666** [Macrobase-tech/MKS-DLC32#23]
В этой версии не видит окружение WI FI
[V2.20_H35_2022_1101_N_ZX_002.bin](https://github.com/Macrobase-tech/MKS-DLC32/blob/main/MKS%20DLC32%2BTS35/Firmware/Laser/Normal/Board_V2.0/V2.20_H35_2022_1101_N_ZX_002.bin)

**Comment by Macrobase-tech** [comment]
Hello,it's available and work.
please try another bin or check home wifi




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Macrobase-tech/MKS-DLC32"                                                                                    ***@***.***&gt;;
Date:&nbsp;Thu, Apr 6, 2023 03:50 AM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[Macrobase-tech/MKS-DLC32] V2.20_H35_2022_1101_N_ZX_002 - WI FI (Issue #23)





 
В этой версии не видит окружение WI FI
 V2.20_H35_2022_1101_N_ZX_002.bin

**Comment by Babaika1987** [comment]
Я ставил эти сборки 
V2.0.8_H35_20220105_N.bin рабочий поиск wi fi
V2.10_H35_2022_0621_N_ZX_001.bin рабочий поиск wi fi

V2.20_H35_2022_1101_N_ZX_002.bin тут поиск Wi-Fi не работает ( у меня дома 4 сети Wi-Fi) не видит ни одной просто пусто

**Comment by Babaika1987** [comment]
https://youtu.be/hEWaz3rLE0k
https://youtu.be/2zPesD0v2Wk

**Comment by Babaika1987** [comment]
Другая прошивка решит эту проблему
V2.30_H35_2022_1223_N_ZX_001.bin

**Comment by Macrobase-tech** [comment]
1005918473
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Macrobase-tech/MKS-DLC32"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sun, Apr 9, 2023 11:13 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [Macrobase-tech/MKS-DLC32] V2.20_H35_2022_1101_N_ZX_002 - WI FI (Issue #23)





 
Другая прошивка решит эту проблему
 V2.30_H35_2022_1223_N_ZX_001.bin
