### ISSUE TITLE
Zero Point Search

### ISSUE THREAD

**Issue by Babaika1987** [Macrobase-tech/MKS-DLC32#24]
https://github.com/Macrobase-tech/MKS-DLC32/blob/main/MKS%20DLC32%2BTS35/Firmware/Laser/Normal/Board_V2.0/V2.0.8_H35_20220105_N.bin

When the machine is looking for a zero point, it makes a 1mm indent from the endpoints and should reset these coordinates, but it does not do this and in the coordinates the state is 1mm in X and Y if you press home, it returns to zero and presses the end point.

**Comment by Macrobase-tech** [comment]
Sorry,i can't understand the issue you desrcibe.
Is it possible to show in video?




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Macrobase-tech/MKS-DLC32"                                                                                    ***@***.***&gt;;
Date:&nbsp;Fri, Apr 7, 2023 11:39 AM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[Macrobase-tech/MKS-DLC32] Zero Point Search (Issue #24)





 
https://github.com/Macrobase-tech/MKS-DLC32/blob/main/MKS%20DLC32%2BTS35/Firmware/Laser/Normal/Board_V2.0/V2.0.8_H35_20220105_N.bin
 
When the machine is looking for a zero point, it makes a 1mm indent from the endpoints and should reset these coordinates, but it does not do this and in the coordinates the state is 1mm in X and Y if you press home, it returns to zero and presses the end point.

**Comment by Babaika1987** [comment]
Ok

**Comment by Babaika1987** [comment]
Я решил проблему прошивкой 2.30ver

**Comment by Macrobase-tech** [comment]
That's wonderful


1005918473
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Macrobase-tech/MKS-DLC32"                                                                                    ***@***.***&gt;;
Date:&nbsp;Sun, Apr 9, 2023 09:47 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [Macrobase-tech/MKS-DLC32] Zero Point Search (Issue #24)





 
Я решил проблему прошивкой 2.30ver
