### ISSUE TITLE
Configuring the firmware for a specific machine.

### ISSUE THREAD

**Issue by Sim-26356** [Macrobase-tech/MKS-DLC32#35]
Hello. You can send an email simbiot78.s7@gmail.com source code for firmware version V2.1.0_H35_20220526_02_N_CNC (MKS DLC 32 + TS 35).

**Comment by Macrobase-tech** [comment]
Hello,here is the source code.
https://github.com/Macrobase-tech/MKS-DLC32/blob/main/DLC32-Firmware%20Code.zip




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "Macrobase-tech/MKS-DLC32"                                                                                    ***@***.***&gt;;
Date:&nbsp;Fri, Nov 10, 2023 10:47 PM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[Macrobase-tech/MKS-DLC32] Configuring the firmware for a specific machine. (Issue #35)





 
Hello. You can send an email ***@***.*** source code for firmware version V2.1.0_H35_20220526_02_N_CNC (MKS DLC 32 + TS 35).
